### ISSUE TITLE
Error 404 when run in server after 'npm start'

### ISSUE THREAD

**Issue by juancash** [PiyushDixit96/binance-spot-order-notification-heroku#6]
When I run the project in Heroku all works fine, but when I try run in my own server I got a 404 error after the 'npm start'. What I missing?

This is the error message:

```
23/5/2022, 7:01:11 pm GMT+1 - Server started on 3000 port
23/5/2022, 7:01:11 pm GMT+1 - Monitoring Spot User Order Data for binance.com
Unhandled rejection Error: 404:
{"ok":false,"error_code":404,"description":"Not Found"}
    at Request.then.resp (/home/ubuntu/binance-tracking/index.js:174:19)
    at tryCatcher (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/binance-tracking/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by juancash** [comment]
It was a missing entry in my .env file.
Thanks.
